// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATB7rtwMCFi41pKAalah8L0G0fBuTjswU',
    appId: '1:1011998745801:android:4409a0be62c33c206a1918',
    messagingSenderId: '1011998745801',
    projectId: 'foodies-6fe08',
    databaseURL: 'https://foodies-6fe08-default-rtdb.firebaseio.com',
    storageBucket: 'foodies-6fe08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKYYXg0dqieVM-V_ZwNjX6p5IBlKYl8dg',
    appId: '1:1011998745801:ios:ccf7a3c4a55a6b126a1918',
    messagingSenderId: '1011998745801',
    projectId: 'foodies-6fe08',
    databaseURL: 'https://foodies-6fe08-default-rtdb.firebaseio.com',
    storageBucket: 'foodies-6fe08.appspot.com',
    iosClientId: '1011998745801-iev31j3jm1vf5c8io9eofcdjk6flpmuk.apps.googleusercontent.com',
    iosBundleId: 'com.foodies.customer.ios',
  );
}
